import type { Metadata } from "next";
import "./globals.css";
import db from "@/lib/supabase/db";
import { ThemeProvider } from "@/lib/providers/next-theme-provider";
import { DM_Sans } from 'next/font/google'
import { AppStateProvider } from "@/lib/providers/state-provider";


const inter = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ThinkBoard',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  /**
 * CHALLENGES 
  1 Files keep reseting when we change between workspaces.
  2 Real time workspaces
  3 WHEN YOU trash a folder files are also trashed but now when you try to
  4 WHEN SOMEONE IS ADDED AS A WORKSPACE COLLABORATOR THEN you need to create the real time feature.
  5 Include number of collaborators in Plan Usage
 */

  return (
    <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
      <body
        className={`${inter.className} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <AppStateProvider>
            {children}
          </AppStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
